#!/bin/bash

# Manual Pro Tier Testing Script
echo "AI Search Analyzer - Pro Tier Manual Testing"
echo "==========================================="
echo ""
echo "Prerequisites:"
echo "1. Dev server running on http://localhost:3000"
echo "2. NEXT_PUBLIC_ENABLE_PRO_FEATURES=true in .env.local"
echo "3. OpenAI API key configured"
echo ""
echo "Testing Instructions:"
echo ""
echo "Step 1: Enable Pro Access"
echo "------------------------"
echo "1. Open http://localhost:3000 in your browser"
echo "2. Open DevTools Console (F12)"
echo "3. Run: localStorage.setItem('isPro', 'true')"
echo "4. Refresh the page"
echo ""
echo "Step 2: Test Each URL"
echo "---------------------"
echo ""
echo "Test URL 1: https://www.adyen.com"
echo "  a) Enter URL in free tier analyzer"
echo "  b) Note the score and basic analysis"
echo "  c) Click 'Unlock Full Analysis'"
echo "  d) Verify redirect to /pro?url=..."
echo "  e) Test Deep Analysis tab:"
echo "     - Check technical fixes list"
echo "     - Check content improvements"
echo "     - Verify decimal scores"
echo "  f) Test AI Done-for-You tab:"
echo "     - Wait for rewrite to complete"
echo "     - Check improvements made"
echo "     - Verify data points added"
echo ""
echo "Test URL 2: https://en.wikipedia.org/wiki/Artificial_intelligence"
echo "  - Repeat steps a-f above"
echo ""
echo "Test URL 3: https://www.nytimes.com"
echo "  - Repeat steps a-f above"
echo ""
echo "Test URL 4: https://docs.python.org"
echo "  - Repeat steps a-f above"
echo ""
echo "Test URL 5: https://www.healthline.com"
echo "  - Repeat steps a-f above"
echo ""
echo "Step 3: Quality Checks"
echo "----------------------"
echo "For each URL, evaluate:"
echo "□ Scores align with content quality"
echo "□ Technical fixes are actionable"
echo "□ Content suggestions are relevant"
echo "□ AI rewrite improves the content"
echo "□ No errors or timeouts"
echo "□ Professional UI/UX"
echo ""
echo "Step 4: Document Findings"
echo "------------------------"
echo "Update docs/PRO_TIER_TESTING_REPORT.md with results"
echo ""
echo "Press Enter to open the browser..."
read

# Open browser
open http://localhost:3000

echo ""
echo "Testing in progress..."
echo "Update the report as you test each URL."